name: CMake

on:
  push:
    #branches: [ "develop" ]
  pull_request:
    #branches: [ "develop" ]

env:
  BUILD_TYPE: Release

jobs:
  test:
    strategy:
      matrix:
        arch:
          - win64
          - win32
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
          sdk: 7
          toolset: 14.0
          vsversion: 2015
      - name: Clone into PsyDoom Dir
        run: git clone https://github.com/BodbDearg/PsyDoom -b develop
      - name: Build something requiring CL.EXE
        run: |
          cmake -S PsyDoom -B build -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build build --config ${{env.BUILD_TYPE}}
